# Generated by Django 4.1.3 on 2023-09-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_peca', models.CharField(max_length=40)),
                ('marca_peca', models.CharField(max_length=40)),
                ('valor_peca', models.FloatField()),
                ('codigo_barras_peca', models.CharField(max_length=13)),
                ('disponibilidade_peca', models.BooleanField()),
            ],
        ),
    ]
