# Generated by Django 4.1.3 on 2023-09-21 20:16

from django.db import migrations, models
import peca.validator


class Migration(migrations.Migration):

    dependencies = [
        ('peca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='codigo_barras_peca',
            field=models.CharField(max_length=13, validators=[peca.validator.validateCodBarras]),
        ),
        migrations.AlterField(
            model_name='peca',
            name='nome_peca',
            field=models.CharField(max_length=40, validators=[peca.validator.validateNome]),
        ),
        migrations.AlterField(
            model_name='peca',
            name='valor_peca',
            field=models.FloatField(validators=[peca.validator.validatePreco]),
        ),
    ]
