# Generated by Django 4.1.3 on 2023-09-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True, unique=True)),
                ('cpf', models.CharField(max_length=11, null=True, unique=True)),
                ('endereco', models.CharField(max_length=100, null=True)),
                ('data_nascimento', models.DateField()),
                ('usernome', models.CharField(max_length=40, null=True, unique=True)),
                ('cargo', models.CharField(choices=[('Gerente', 'Gerente'), ('Funcionario', 'Funcionario')], max_length=50, null=True)),
            ],
        ),
    ]
