# Generated by Django 4.1.3 on 2023-09-21 02:12

from django.db import migrations, models
import usuario.validator


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[usuario.validator.validateCpf]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(validators=[usuario.validator.validateDate]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True, validators=[usuario.validator.validateEmail]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(max_length=100, null=True, validators=[usuario.validator.validateEndereco]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=100, null=True, validators=[usuario.validator.validateNome, usuario.validator.validateNoDigits]),
        ),
    ]
